rule all:
    input:
        "output1.txt",
        "output2.txt",
        "combined.txt",


rule create_file:
    output:
        "output{num}.txt",
    shell:
        """
        echo 'Content from file {wildcards.num}' > {output}
        sleep 1
        """

rule combine_files:
    input:
        "output1.txt",
        "output2.txt",
    output:
        "combined.txt",
    shell:
        "cat {input} > {output}"
