rule all:
    input:
        "output1.1.txt",
        "output2.2.txt",
        "combined.txt",
        "fail.txt"


rule create_file:
    output:
        "output{num}.{pandas}.txt"
    message:
        "Test message"
    shell:
        """
        echo 'Content from file {wildcards.num} and written to be kinda long the quick brown fox jumps over the lazy dog' > {output}
        sleep 1
        """

rule forced_failure:
    output:
        "fail.txt"
    log:
        "logs/fail.log"
    shell:
        "XXechoXX 'this that' > {output} 2> {log}"

rule combine_files:
    input:
        "output1.1.txt",
        "output2.2.txt"
    output:
        "combined.txt"
    message:
        "Test message"
    conda:
        "envs/conda.yaml"
    shell:
        "cat {input} > {output}"
